### ISSUE TITLE
How to get pose from VIVE tracker?

### ISSUE THREAD

**Issue by msvargas** [ebadier/ViveTrackers#2]
Hi @ebadier, can you help me please?

I have this tracker: https://www.vive.com/us/accessory/tracker3/

I need for my project to get the rotational and positional location of the tracker

Please could you help me and tell me the easiest way that we can get the position of the tracker in a C# script?

That by sending a command through C# script how can we get the above data at a certain time?

Thanks in advance!

**Comment by ebadier** [comment]
Hi @msvargas,

Please do the following:
1. Open SteamVR, configure your tracking space, connect your Vive Trackers, and leave SteamVR running in the background.
2. Open the ViveTrackersTest scene in Unity and press Play.
3. Please see the script ViveTrackersTest.cs, especially the Update() function (line 52-77) : you will see that you can press F1/F5/F6/F7/F8 keys. 
- The first line of the Update() function updates all trackers position & rotation (see ViveTrackersManager.cs line 93-109).
ViveTrackersManager contains a list of all instances of ViveTracker objects, named "_trackers".
You can access the last position & rotation of ViveTracker objects using transform.localPosition & transform.localRotation.
- The F5 key is to refresh the list of currently connected trackers.
4. Optionally, ViveTrackersManager can use only a restricted set of Vive Trackers using the file ViveTrackers.csv (see [documentation/"Keep Vive Trackers identification consistent during runtime"](https://github.com/ebadier/ViveTrackers/blob/master/Doc/ViveTrackersDocumentation.pdf)

Best regards.

**Comment by msvargas** [comment]
Thank so much @ebadier I will try it

**Comment by msvargas** [comment]
Hi @ebadier sorry to bother you again, but do you know how to run and read VIVE Tracker without HDM? I was trying many tutorials but none of them works for me, I really appreciate any help, thanks!

Like this: https://github-wiki-see.page/m/corycorvus/VIVE-Tracker-Wiki/wiki/SteamVR-tracking-without-HMD#steamvr-tracking-without-hmd

**Comment by ebadier** [comment]
Hi @msvargas,

Please see the documentation - page 7 [Running SteamVR with Vive Trackers only (no HMD)](https://github.com/ebadier/ViveTrackers/blob/master/Doc/ViveTrackersDocumentation.pdf)

Best regards.
