### ISSUE TITLE
How to get the button input on the Tracker?

### ISSUE THREAD

**Issue by mrmaarten** [ebadier/ViveTrackers#3]
I am new to Unity, but I thought it might be handy for other people as well.

I want to attach buttons to the Trackers via the pogo pins.

Is there a way to reveal that data per Tracker?

I found this script, but I am not able to intregrate it in your Tracker System (still learning...)
https://unity3d.college/2017/08/14/using-htc-vive-tracker-pogo-pins-unity3d/

using UnityEngine;

public class TriggerTester : MonoBehaviour
{
    private SteamVR_TrackedObject trackedObject;

    [SerializeField]
    private bool trigger;
    [SerializeField]
    private bool trackpad;
    [SerializeField]
    private bool grip;
    [SerializeField]
    public bool menu;

    private void Start()
    {
        trackedObject = GetComponent<SteamVR_TrackedObject>();
    }

    private void Update()
    {
        var device = SteamVR_Controller.Input((int)trackedObject.index);

        trigger = device.GetPress(Valve.VR.EVRButtonId.k_EButton_SteamVR_Trigger);
        grip = device.GetPress(Valve.VR.EVRButtonId.k_EButton_Grip);
        trackpad = device.GetPress(Valve.VR.EVRButtonId.k_EButton_SteamVR_Touchpad);
        menu = device.GetPress(Valve.VR.EVRButtonId.k_EButton_ApplicationMenu);
    }
}

**Comment by ebadier** [comment]
Hi @mrmaarten,

Thanks for your message.

I just added the requested feature.

To try it, just set ViveTrackersManager.enableButtons = true, in the Unity Editor.
You will be able to see messages in the console everytime the Grip/Trigger/TouchPad/Menu buttons are pressed/released.

I didn't test the feature for the moment, so it should be great if you can let me know the results of your tests.
There might be something wrong : see my comment line 119 in [ViveTrackersManager.cs](https://github.com/ebadier/ViveTrackers/blob/master/Scripts/ViveTrackersManager.cs)

Best regards.

Emmanuel

**Comment by mrmaarten** [comment]
hi Emmanuel,

thanks very much for this!

Enabling the buttons does not print anything out in the console. Also when Playing the scene, stopping it, and then Playing it again, the trackers are not found again. Even if I press F5 (it says again that no trackers are found) Before that was not an issue... but I don't see any errors in the console...

**Comment by ebadier** [comment]
Thanks for your feedback.
I will be able to test on my side tomorrow, and fix things.

**Comment by ebadier** [comment]
Hi @mrmaarten,

I fixed bugs.
Could you please let me know if everything work now on your side ?

Thanks.

**Comment by mrmaarten** [comment]
Hi Emmanuel,

yes it is working! I see the button states in the console, and disabling/ enabling works. Also all the connection problems are gone.

Thanks for the work!
